### ISSUE TITLE
0.9.1 version cannot be compiled

### ISSUE THREAD

**Issue by fly-studio** [goplus/igop#188]
igop 0.9.1

\load\embed_go116.go:94:29: not enough arguments in call to r.Load

```
r.Load(bp.Dir, v) 
```

\go\pkg\mod\github.com\visualfc\goembed@v0.3.0\resolve.go
```
Load(dir string, fset *token.FileSet, em *Embed) ([]*File, error)
```

**Comment by visualfc** [comment]
igop main version use goembed v0.3.x
v0.9.1 use goembed v0.2.7
