### ISSUE TITLE
How to include a local package,When I using igop

### ISSUE THREAD

**Issue by lx217197** [goplus/igop#213]
dir1/flie.go=`package a xxxxx`
dir2/file.go = `package b import a xxxxxxx`

**Comment by lx217197** [comment]
igop.RunFile("main.go","dir2/file.go")

**Comment by visualfc** [comment]
use ctx.AddImportFile or ctx.AddImportDir

igop.TestAddImport
https://github.com/goplus/igop/blob/main/interp_test.go#L2230
igop.TestAddImportDir
https://github.com/goplus/igop/blob/main/interp_test.go#L2263

**Comment by lx217197** [comment]
I have seen the function and the sample，But the scripts dir are not always in my control. Is there a way to organize directories on the script code side

**Comment by visualfc** [comment]
> @visualfc I have seen the function and the sample，But the scripts dir are not always in my control. Is there a way to organize directories on the script code side

use go.mod

**Comment by lx217197** [comment]
@visualfc I am surprised that igop can support go mod, it's amazing
