### ISSUE TITLE
Some native func / //go:linkname not work

### ISSUE THREAD

**Issue by secoba** [goplus/igop#272]
Such as "time" module not work well

![image](https://github.com/goplus/igop/assets/25523634/29f8cb2a-b01f-46b2-a767-0d70f16e57fc)

"time" module had registered

vendor/github.com/goplus/igop/pkg/time/go121_export.go:17
![image](https://github.com/goplus/igop/assets/25523634/9ca3a12a-d2d3-43f7-bf3c-41bb6de6338a)

![image](https://github.com/goplus/igop/assets/25523634/506960b5-72b5-479a-8e3e-a224da0f1841)

![image](https://github.com/goplus/igop/assets/25523634/0830396f-c5e6-4315-839c-11db37c9b650)

**Comment by visualfc** [comment]
import (
	"github.com/goplus/igop"
	_ "github.com/goplus/igop/pkg/fmt"
	_ "github.com/goplus/igop/pkg/time"
)
